//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XinViec.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XinViec.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _10219171_income_salary_dollar_money_bag_profit_icon {
            get {
                object obj = ResourceManager.GetObject("10219171_income_salary_dollar_money bag_profit_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _10219171_income_salary_dollar_money_bag_profit_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("10219171_income_salary_dollar_money bag_profit_icon (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _10219171_income_salary_dollar_money_bag_profit_icon__2_ {
            get {
                object obj = ResourceManager.GetObject("10219171_income_salary_dollar_money bag_profit_icon (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _10219188_business_briefcase_job_work_suitcase_icon {
            get {
                object obj = ResourceManager.GetObject("10219188_business_briefcase_job_work_suitcase_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _103781_profile_edit_user_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("_103781_profile_edit_user_icon__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _103781_profile_edit_user_icon__2_ {
            get {
                object obj = ResourceManager.GetObject("103781_profile_edit_user_icon (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _10635564_file_document_upload_submit_file_upload_icon {
            get {
                object obj = ResourceManager.GetObject("10635564_file_document_upload_submit_file upload_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1071016_location_gps_pin_marker_icon {
            get {
                object obj = ResourceManager.GetObject("1071016_location_gps_pin marker_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1078687_logo_media_phone_social_icon {
            get {
                object obj = ResourceManager.GetObject("1078687_logo_media_phone_social_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1078687_logo_media_phone_social_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("1078687_logo_media_phone_social_icon (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1078687_logo_media_phone_social_icon__2_ {
            get {
                object obj = ResourceManager.GetObject("1078687_logo_media_phone_social_icon (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _10863200_fi_br_chat_arrow_grow_icon {
            get {
                object obj = ResourceManager.GetObject("10863200_fi_br_chat_arrow_grow_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1110970_essential_grid_set_sort_icon__2_ {
            get {
                object obj = ResourceManager.GetObject("1110970_essential_grid_set_sort_icon (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _11121097_fi_rr_chat_arrow_grow_icon {
            get {
                object obj = ResourceManager.GetObject("11121097_fi_rr_chat_arrow_grow_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _134226_back_arrow_left_icon__9_ {
            get {
                object obj = ResourceManager.GetObject("134226_back_arrow_left_icon (9)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1343436_add_circle_download_plus_icon {
            get {
                object obj = ResourceManager.GetObject("1343436_add_circle_download_plus_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1564491_add_create_new_plus_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("_1564491_add_create_new_plus_icon__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1564491_add_create_new_plus_icon__1_1 {
            get {
                object obj = ResourceManager.GetObject("_1564491_add_create_new_plus_icon__1_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1564504_email_letter_mail_message_icon {
            get {
                object obj = ResourceManager.GetObject("1564504_email_letter_mail_message_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1564520_code_open_password_icon {
            get {
                object obj = ResourceManager.GetObject("_1564520_code_open_password_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1564528_fly_messager_send_communication_email_icon {
            get {
                object obj = ResourceManager.GetObject("1564528_fly_messager_send_communication_email_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1564528_fly_messager_send_communication_email_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("1564528_fly_messager_send_communication_email_icon (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1564534_customer_man_user_account_profile_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("_1564534_customer_man_user_account_profile_icon__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1564534_customer_man_user_account_profile_icon__2_ {
            get {
                object obj = ResourceManager.GetObject("1564534_customer_man_user_account_profile_icon (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1651909_calendar_christmas_date_icon {
            get {
                object obj = ResourceManager.GetObject("1651909_calendar_christmas_date_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _171279_alarm_clock_bell_time_icon {
            get {
                object obj = ResourceManager.GetObject("171279_alarm_clock_bell_time_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _172626_user_male_icon {
            get {
                object obj = ResourceManager.GetObject("172626_user_male_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _172626_user_male_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("172626_user_male_icon (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _172626_user_male_icon__2_ {
            get {
                object obj = ResourceManager.GetObject("172626_user_male_icon (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _2024660_call_contact_us_contacts_phone_support_icon {
            get {
                object obj = ResourceManager.GetObject("2024660_call_contact us_contacts_phone_support_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _2093659_update_arrow_refresh_renew_synchronize_icon {
            get {
                object obj = ResourceManager.GetObject("2093659_update_arrow_refresh_renew_synchronize_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _2400503_birthday_cake_celebration_christmas_cake_party_wedding_cake_icon {
            get {
                object obj = ResourceManager.GetObject("2400503_birthday cake_celebration_christmas cake_party_wedding cake_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _2849794_plane_paper_airplane_send_airplane_multimedia_icon {
            get {
                object obj = ResourceManager.GetObject("2849794_plane_paper airplane_send_airplane_multimedia_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _287695_location_icon__2_ {
            get {
                object obj = ResourceManager.GetObject("287695_location_icon (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _287695_location_icon__3_ {
            get {
                object obj = ResourceManager.GetObject("287695_location_icon (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _287695_location_icon__4_ {
            get {
                object obj = ResourceManager.GetObject("287695_location_icon (4)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3017938_adapt_alter_compose_correct_edit_icon {
            get {
                object obj = ResourceManager.GetObject("3017938_adapt_alter_compose_correct_edit_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3017938_adapt_alter_compose_correct_edit_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("3017938_adapt_alter_compose_correct_edit_icon (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3018559_design_formation_layout_option_organization_icon {
            get {
                object obj = ResourceManager.GetObject("3018559_design_formation_layout_option_organization_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _309035_user_account_human_person_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("309035_user_account_human_person_icon (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _326554_cancel_icon__2_ {
            get {
                object obj = ResourceManager.GetObject("326554_cancel_icon (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _326688_floppy_save_guardar_icon__2_ {
            get {
                object obj = ResourceManager.GetObject("326688_floppy_save_guardar_icon (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _326688_floppy_save_guardar_icon__3_ {
            get {
                object obj = ResourceManager.GetObject("326688_floppy_save_guardar_icon (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3507755_appointment_calendar_date_day_iconoteka_icon {
            get {
                object obj = ResourceManager.GetObject("3507755_appointment_calendar_date_day_iconoteka_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3507755_appointment_calendar_date_day_iconoteka_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("3507755_appointment_calendar_date_day_iconoteka_icon (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3669395_call_ic_icon {
            get {
                object obj = ResourceManager.GetObject("3669395_call_ic_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3671753_currency_dollar_icon {
            get {
                object obj = ResourceManager.GetObject("3671753_currency_dollar_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3671803_closed_lock_icon {
            get {
                object obj = ResourceManager.GetObject("3671803_closed_lock_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3671905_show_view_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("_3671905_show_view_icon__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3671905_show_view_icon__2_ {
            get {
                object obj = ResourceManager.GetObject("_3671905_show_view_icon__2_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _372903_username_name_full_user_round_icon {
            get {
                object obj = ResourceManager.GetObject("372903_username_name_full_user_round_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3844425_can_trash_icon {
            get {
                object obj = ResourceManager.GetObject("_3844425_can_trash_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3844425_can_trash_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("3844425_can_trash_icon (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3844425_can_trash_icon__2_ {
            get {
                object obj = ResourceManager.GetObject("3844425_can_trash_icon (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3844425_can_trash_icon__2_1 {
            get {
                object obj = ResourceManager.GetObject("3844425_can_trash_icon (2)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3844425_can_trash_icon__3_ {
            get {
                object obj = ResourceManager.GetObject("3844425_can_trash_icon (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3844425_can_trash_icon__3_1 {
            get {
                object obj = ResourceManager.GetObject("3844425_can_trash_icon (3)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3844432_magnifier_search_zoom_icon {
            get {
                object obj = ResourceManager.GetObject("3844432_magnifier_search_zoom_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3844432_magnifier_search_zoom_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("3844432_magnifier_search_zoom_icon (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3844439_gear_setting_settings_wheel_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("_3844439_gear_setting_settings_wheel_icon__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3844439_gear_setting_settings_wheel_icon__2_ {
            get {
                object obj = ResourceManager.GetObject("3844439_gear_setting_settings_wheel_icon (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3844444_dot_menu_more_option_icon {
            get {
                object obj = ResourceManager.GetObject("3844444_dot_menu_more_option_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3844444_dot_menu_more_option_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("3844444_dot_menu_more_option_icon (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3844444_dot_menu_more_option_icon__1_1 {
            get {
                object obj = ResourceManager.GetObject("3844444_dot_menu_more_option_icon (1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3884113_growth_income_invest_market_stock_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("3884113_growth_income_invest_market_stock_icon (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3884113_growth_income_invest_market_stock_icon__2_ {
            get {
                object obj = ResourceManager.GetObject("3884113_growth_income_invest_market_stock_icon (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3890929_chart_growth_invest_market_stock_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("_3890929_chart_growth_invest_market_stock_icon__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3952184_building_city_company_construction_icon {
            get {
                object obj = ResourceManager.GetObject("3952184_building_city_company_construction_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3952184_building_city_company_construction_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("3952184_building_city_company_construction_icon (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3952184_building_city_company_construction_icon__2_ {
            get {
                object obj = ResourceManager.GetObject("3952184_building_city_company_construction_icon (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3952184_building_city_company_construction_icon__3_ {
            get {
                object obj = ResourceManager.GetObject("3952184_building_city_company_construction_icon (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3952925_archive_document_folder_note_icon {
            get {
                object obj = ResourceManager.GetObject("3952925_archive_document_folder_note_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3994379_lock_padlock_privacy_protection_security_icon {
            get {
                object obj = ResourceManager.GetObject("3994379_lock_padlock_privacy_protection_security_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3994383_email_envelope_letter_mail_newsletter_icon {
            get {
                object obj = ResourceManager.GetObject("3994383_email_envelope_letter_mail_newsletter_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3994402_interface_message_paper_plane_send_sent_icon__2_ {
            get {
                object obj = ResourceManager.GetObject("3994402_interface_message_paper plane_send_sent_icon (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3994402_interface_message_paper_plane_send_sent_icon__4_ {
            get {
                object obj = ResourceManager.GetObject("3994402_interface_message_paper plane_send_sent_icon (4)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3994402_interface_message_paper_plane_send_sent_icon__4_1 {
            get {
                object obj = ResourceManager.GetObject("3994402_interface_message_paper plane_send_sent_icon (4)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3994402_interface_message_paper_plane_send_sent_icon__5_ {
            get {
                object obj = ResourceManager.GetObject("3994402_interface_message_paper plane_send_sent_icon (5)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3994402_interface_message_paper_plane_send_sent_icon__5_1 {
            get {
                object obj = ResourceManager.GetObject("3994402_interface_message_paper plane_send_sent_icon (5)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3994402_interface_message_paper_plane_send_sent_icon__6_ {
            get {
                object obj = ResourceManager.GetObject("3994402_interface_message_paper plane_send_sent_icon (6)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3994413_above_arrow_navigation_top_up_icon {
            get {
                object obj = ResourceManager.GetObject("3994413_above_arrow_navigation_top_up_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _403022_business_man_male_user_avatar_profile_icon {
            get {
                object obj = ResourceManager.GetObject("403022_business man_male_user_avatar_profile_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _4115235_exit_logout_sign_out_icon {
            get {
                object obj = ResourceManager.GetObject("_4115235_exit_logout_sign_out_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _4168568_data_upload_download_file_upgrade_icon {
            get {
                object obj = ResourceManager.GetObject("4168568_data_upload_download_file_upgrade_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _416920_curriculum_cv_profile_sheet_vitae_icon {
            get {
                object obj = ResourceManager.GetObject("416920_curriculum_cv_profile_sheet_vitae_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _416920_curriculum_cv_profile_sheet_vitae_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("416920_curriculum_cv_profile_sheet_vitae_icon (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _4213408_address_book_contact_contacts_human_icon {
            get {
                object obj = ResourceManager.GetObject("4213408_address_book_contact_contacts_human_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _4308246_business_dollar_grow_growing_growth_icon {
            get {
                object obj = ResourceManager.GetObject("4308246_business_dollar_grow_growing_growth_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _4308246_business_dollar_grow_growing_growth_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("4308246_business_dollar_grow_growing_growth_icon (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _4308246_business_dollar_grow_growing_growth_icon__2_ {
            get {
                object obj = ResourceManager.GetObject("4308246_business_dollar_grow_growing_growth_icon (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _4550857_email_gmail_mail_sending_yahoo_icon {
            get {
                object obj = ResourceManager.GetObject("4550857_email_gmail_mail_sending_yahoo_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _4550857_email_gmail_mail_sending_yahoo_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("4550857_email_gmail_mail_sending_yahoo_icon (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _4550857_email_gmail_mail_sending_yahoo_icon__2_ {
            get {
                object obj = ResourceManager.GetObject("4550857_email_gmail_mail_sending_yahoo_icon (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _4550857_email_gmail_mail_sending_yahoo_icon__3_ {
            get {
                object obj = ResourceManager.GetObject("4550857_email_gmail_mail_sending_yahoo_icon (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _4737448_account_user_avatar_profile_icon {
            get {
                object obj = ResourceManager.GetObject("4737448_account_user_avatar_profile_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _4817169_china_policy_usa_american_first_china_and_us_trade_war_icon {
            get {
                object obj = ResourceManager.GetObject("4817169_china_policy_usa_american first_china and us trade war_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _5402373_write_modify_tool_edit_pen_icon {
            get {
                object obj = ResourceManager.GetObject("_5402373_write_modify_tool_edit_pen_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _5402373_write_modify_tool_edit_pen_icon__2_1 {
            get {
                object obj = ResourceManager.GetObject("_5402373_write_modify_tool_edit_pen_icon__2_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _5402373_write_modify_tool_edit_pen_icon__3_ {
            get {
                object obj = ResourceManager.GetObject("5402373_write_modify_tool_edit_pen_icon (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _5402373_write_modify_tool_edit_pen_icon__4_ {
            get {
                object obj = ResourceManager.GetObject("5402373_write_modify_tool_edit_pen_icon (4)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _5402373_write_modify_tool_edit_pen_icon__5_ {
            get {
                object obj = ResourceManager.GetObject("5402373_write_modify_tool_edit_pen_icon (5)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _5402373_write_modify_tool_edit_pen_icon__5_1 {
            get {
                object obj = ResourceManager.GetObject("5402373_write_modify_tool_edit_pen_icon (5)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _6598158_balance_compare_justice_scale_weight_icon {
            get {
                object obj = ResourceManager.GetObject("6598158_balance_compare_justice_scale_weight_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _6673747_care_doctor_health_healthcare_history_icon {
            get {
                object obj = ResourceManager.GetObject("6673747_care_doctor_health_healthcare_history_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _6843095_analysis_business_chart_manage_management_icon {
            get {
                object obj = ResourceManager.GetObject("6843095_analysis_business_chart_manage_management_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _7215642_resume_business_cv_work_job_icon {
            get {
                object obj = ResourceManager.GetObject("7215642_resume_business_cv_work_job_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _7215642_resume_business_cv_work_job_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("7215642_resume_business_cv_work_job_icon (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _7217425_office_business_work_workplace_home_icon {
            get {
                object obj = ResourceManager.GetObject("7217425_office_business_work_workplace_home_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _7217425_office_business_work_workplace_home_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("7217425_office_business_work_workplace_home_icon (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _7217867_resume_business_cv_work_job_icon {
            get {
                object obj = ResourceManager.GetObject("7217867_resume_business_cv_work_job_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _7217867_resume_business_cv_work_job_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("7217867_resume_business_cv_work_job_icon (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _7217867_resume_business_cv_work_job_icon1 {
            get {
                object obj = ResourceManager.GetObject("7217867_resume_business_cv_work_job_icon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _7218126_resume_business_cv_work_job_icon {
            get {
                object obj = ResourceManager.GetObject("7218126_resume_business_cv_work_job_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _7295022_group_team_people_avatar_profile_icon {
            get {
                object obj = ResourceManager.GetObject("7295022_group_team_people_avatar_profile_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _7492230_new_file_add_create_icon {
            get {
                object obj = ResourceManager.GetObject("7492230_new_file_add_create_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _7695997_document_business_paper_file_paperwork_icon {
            get {
                object obj = ResourceManager.GetObject("7695997_document_business_paper_file_paperwork_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _7695997_document_business_paper_file_paperwork_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("7695997_document_business_paper_file_paperwork_icon (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _7695997_document_business_paper_file_paperwork_icon__2_ {
            get {
                object obj = ResourceManager.GetObject("7695997_document_business_paper_file_paperwork_icon (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _7738935_history_time_clock_schedule_event_icon {
            get {
                object obj = ResourceManager.GetObject("7738935_history_time_clock_schedule_event_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _7830799_phone_actions_ring_icon {
            get {
                object obj = ResourceManager.GetObject("7830799_phone_actions_ring_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _7853748_account_settings_kashifarif_configuration_profile_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("_7853748_account_settings_kashifarif_configuration_profile_icon__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _7853748_account_settings_kashifarif_configuration_profile_icon__2_ {
            get {
                object obj = ResourceManager.GetObject("7853748_account_settings_kashifarif_configuration_profile_icon (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _8483277_arrow_arrows_direction_transfer_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("8483277_arrow_arrows_direction_transfer_icon (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _8541584_arrow_circle_left_icon {
            get {
                object obj = ResourceManager.GetObject("8541584_arrow_circle_left_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _8541584_arrow_circle_left_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("8541584_arrow_circle_left_icon (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _8541584_arrow_circle_left_icon__1_1 {
            get {
                object obj = ResourceManager.GetObject("8541584_arrow_circle_left_icon (1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _8541612_check_tick_mark_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("8541612_check_tick_mark_icon (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _8541829_eye_vision_view_icon__2_ {
            get {
                object obj = ResourceManager.GetObject("8541829_eye_vision_view_icon (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _8541829_eye_vision_view_icon__2_1 {
            get {
                object obj = ResourceManager.GetObject("8541829_eye_vision_view_icon (2)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _8541829_eye_vision_view_icon__2_2 {
            get {
                object obj = ResourceManager.GetObject("8541829_eye_vision_view_icon (2)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _8541829_eye_vision_view_icon__3_ {
            get {
                object obj = ResourceManager.GetObject("8541829_eye_vision_view_icon (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _8541835_history_time_icon {
            get {
                object obj = ResourceManager.GetObject("8541835_history_time_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _8541853_home_icon {
            get {
                object obj = ResourceManager.GetObject("8541853_home_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _8665030_business_time_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("8665030_business_time_icon (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _8665299_city_building_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("8665299_city_building_icon (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _8665299_city_building_icon__2_ {
            get {
                object obj = ResourceManager.GetObject("8665299_city_building_icon (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _8665299_city_building_icon__3_ {
            get {
                object obj = ResourceManager.GetObject("8665299_city_building_icon (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _8665423_filter_circle_xmark_icon__5_ {
            get {
                object obj = ResourceManager.GetObject("_8665423_filter_circle_xmark_icon__5_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _8665618_lock_security_icon {
            get {
                object obj = ResourceManager.GetObject("8665618_lock_security_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _8665833_rotate_refresh_icon {
            get {
                object obj = ResourceManager.GetObject("8665833_rotate_refresh_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _8665916_scale_unbalanced_icon {
            get {
                object obj = ResourceManager.GetObject("8665916_scale_unbalanced_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _8674989_ic_fluent_history_regular_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("_8674989_ic_fluent_history_regular_icon__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _8678815_file_history_fill_icon {
            get {
                object obj = ResourceManager.GetObject("8678815_file_history_fill_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _8678936_file_history_document_icon {
            get {
                object obj = ResourceManager.GetObject("8678936_file_history_document_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _8679723_cake_fill_icon {
            get {
                object obj = ResourceManager.GetObject("8679723_cake_fill_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _8684069_folder_file_document_user_profile_icon {
            get {
                object obj = ResourceManager.GetObject("8684069_folder_file_document_user_profile_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _8723062_arrowright_arrow_right_icon {
            get {
                object obj = ResourceManager.GetObject("8723062_arrowright_arrow_right_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _8723062_arrowright_arrow_right_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("8723062_arrowright_arrow_right_icon (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _8723192_arrowleft_arrow_left_icon {
            get {
                object obj = ResourceManager.GetObject("8723192_arrowleft_arrow_left_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _8723192_arrowleft_arrow_left_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("8723192_arrowleft_arrow_left_icon (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _8723192_arrowleft_arrow_left_icon__3_ {
            get {
                object obj = ResourceManager.GetObject("8723192_arrowleft_arrow_left_icon (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _9004671_calendar_date_schedule_event_icon {
            get {
                object obj = ResourceManager.GetObject("9004671_calendar_date_schedule_event_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _9004671_calendar_date_schedule_event_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("9004671_calendar_date_schedule_event_icon (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _9004762_search_find_zoom_magnifier_icon__5_ {
            get {
                object obj = ResourceManager.GetObject("9004762_search_find_zoom_magnifier_icon (5)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _9004762_search_find_zoom_magnifier_icon__5_1 {
            get {
                object obj = ResourceManager.GetObject("9004762_search_find_zoom_magnifier_icon (5)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _9004762_search_find_zoom_magnifier_icon__5_2 {
            get {
                object obj = ResourceManager.GetObject("9004762_search_find_zoom_magnifier_icon (5)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _9004762_search_find_zoom_magnifier_icon__6_ {
            get {
                object obj = ResourceManager.GetObject("9004762_search_find_zoom_magnifier_icon (6)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _9004762_search_find_zoom_magnifier_icon__6_1 {
            get {
                object obj = ResourceManager.GetObject("9004762_search_find_zoom_magnifier_icon (6)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _9004762_search_find_zoom_magnifier_icon__6_2 {
            get {
                object obj = ResourceManager.GetObject("9004762_search_find_zoom_magnifier_icon (6)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _9004762_search_find_zoom_magnifier_icon__6_3 {
            get {
                object obj = ResourceManager.GetObject("9004762_search_find_zoom_magnifier_icon (6)3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _9004762_search_find_zoom_magnifier_icon__6_4 {
            get {
                object obj = ResourceManager.GetObject("9004762_search_find_zoom_magnifier_icon (6)4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _9004762_search_find_zoom_magnifier_icon__6_5 {
            get {
                object obj = ResourceManager.GetObject("9004762_search_find_zoom_magnifier_icon (6)5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _9004773_tick_check_mark_accept_icon {
            get {
                object obj = ResourceManager.GetObject("9004773_tick_check_mark_accept_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _9004801_clock_time_schedule_hour_icon {
            get {
                object obj = ResourceManager.GetObject("9004801_clock_time_schedule_hour_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _9035176_time_clock_icon {
            get {
                object obj = ResourceManager.GetObject("9035176_time_clock_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _9104315_plane_paper_sent_send_mail_icon {
            get {
                object obj = ResourceManager.GetObject("9104315_plane_paper_sent_send_mail_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _9110809_heart_icon {
            get {
                object obj = ResourceManager.GetObject("9110809_heart_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _9111074_heart_icon {
            get {
                object obj = ResourceManager.GetObject("9111074_heart_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _9111074_heart_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("9111074_heart_icon (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _9298902_history_ui_web_user_interface_icon {
            get {
                object obj = ResourceManager.GetObject("9298902_history_ui_web_user interface_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _9599572_venus_mars_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("9599572_venus_mars_icon (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _9599572_venus_mars_icon__2_ {
            get {
                object obj = ResourceManager.GetObject("9599572_venus_mars_icon (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _984759_cancel_close_delete_exit_no_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("984759_cancel_close_delete_exit_no_icon (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anhttcn_macdinh {
            get {
                object obj = ResourceManager.GetObject("anhttcn_macdinh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anhttcn_macdinh1 {
            get {
                object obj = ResourceManager.GetObject("anhttcn_macdinh1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anhttcn_macdinh2 {
            get {
                object obj = ResourceManager.GetObject("anhttcn_macdinh2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AnMK_DoiTenTK {
            get {
                object obj = ResourceManager.GetObject("AnMK_DoiTenTK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CaiDatMatKhau_Dong {
            get {
                object obj = ResourceManager.GetObject("CaiDatMatKhau_Dong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CaiDatMatKhau_Mo {
            get {
                object obj = ResourceManager.GetObject("CaiDatMatKhau_Mo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ChuaYeuThich {
            get {
                object obj = ResourceManager.GetObject("ChuaYeuThich", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap EmptyStar {
            get {
                object obj = ResourceManager.GetObject("EmptyStar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Female {
            get {
                object obj = ResourceManager.GetObject("Female", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FilledStar {
            get {
                object obj = ResourceManager.GetObject("FilledStar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap male {
            get {
                object obj = ResourceManager.GetObject("male", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Screenshot_2024_03_07_073220 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2024_03_07_073220", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Screenshot_2024_03_10_005234 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2024-03-10 005234", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Screenshot_2024_03_14_033927 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2024-03-14 033927", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Screenshot_2024_03_14_034500 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2024-03-14 034500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Screenshot_2024_03_14_0345001 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2024-03-14 0345001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Screenshot_2024_03_18_155513 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2024-03-18 155513", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Screenshot_2024_03_18_1555131 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2024-03-18 1555131", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Screenshot_2024_03_29_081315 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2024-03-29 081315", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Screenshot_2024_03_29_081510 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2024-03-29 081510", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Screenshot_2024_03_29_081624 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2024-03-29 081624", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ThemYeuThich {
            get {
                object obj = ResourceManager.GetObject("ThemYeuThich", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap XemMK_DoiTenTK {
            get {
                object obj = ResourceManager.GetObject("XemMK_DoiTenTK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap YeuThich {
            get {
                object obj = ResourceManager.GetObject("YeuThich", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
